# Generated by Django 4.2.16 on 2026-03-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('p_description', models.CharField(max_length=250)),
                ('p_author', models.CharField(max_length=100)),
                ('p_number', models.BigIntegerField()),
                ('p_stock', models.BigIntegerField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('best_seller', models.CharField(blank=True, max_length=50, null=True)),
                ('p_image', models.ImageField(upload_to='product/')),
                ('p_year', models.CharField(max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
