# Generated by Django 4.2.16 on 2026-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_username', models.CharField(max_length=50)),
                ('a_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_phone', models.CharField(max_length=15, unique=True)),
                ('c_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_store_name', models.CharField(max_length=150, unique=True)),
                ('s_phone', models.CharField(max_length=15)),
                ('s_password', models.CharField(max_length=100)),
                ('s_bank_account', models.CharField(blank=True, max_length=20, null=True)),
                ('s_bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('s_bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
